version: '3.8'

services:
  flask-app:
    build: .
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always
    ports:
      - '9011:5000'
    volumes:
      - .:/home/appuser
    command: gunicorn -b 0.0.0.0:5000 app:app
